### ISSUE TITLE
Error: PlatformException(NULL_FRAME, mFrame is null, null, null)

### ISSUE THREAD

**Issue by greenfire11** [JayKay135/flutter-nothing-glyph-interface#2]
I'am trying to run the example code you provided on my nothing phone 2a, I `changed buildChannel(NothingPhone2.c3)`to `buildChannel(NothingPhone2a.c3)` but the glyph does not light up and i get this error:

```
E/flutter ( 5426): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(NULL_FRAME, mFrame is null, null, null)
E/flutter ( 5426): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 5426): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter ( 5426): <asynchronous suspension>
E/flutter ( 5426): #2      MethodChannelNothingGlyphInterface.animate (package:nothing_glyph_interface/nothing_glyph_interface_method_channel.dart:94:5)
E/flutter ( 5426): <asynchronous suspension>
E/flutter ( 5426): #3      _MyAppState.build.<anonymous closure> (package:glyph/main.dart:70:19)
E/flutter ( 5426): <asynchronous suspension>
```

Glyph debugging is enabled on my device.

**Comment by JayKay135** [comment]
Hi,
thank you for posting this issue.
I think I found and fixed the issue. The initialization for the phone 2a was missing.
I unfortunately do not own a 2a.
Could you check if this fix works for you using
```yaml
nothing_glyph_interface:
    git:
       url: https://github.com/JayKay135/flutter-nothing-glyph-interface.git
```

If it does, I will update the pub.dev package.

**Comment by greenfire11** [comment]
Thanks for the fast response, everything is working fine now :).

**Comment by JayKay135** [comment]
Wonderful. Thanks for your reply
